/Users/deepaksubramanian/Documents/Folder of Documents/XCode/ESAPI_COMPLETE/branches/ESAPI Branch Cuckoo/Pure C functions/ESAPIEncoder/ESAPICEncoder.c File Reference
#include `ESAPICEncoder.h`
#include `ESAPICUrlEncoder.h`
#include <stdio.h>
#include `ESAPICBase64Encoder.h`
#include <string.h>
Functions
ESAPIStringOperation * ESAPICEncode (char *inputString, ESAPIEncodingType typeOfEncoding)
This function is used to encode the given string and return the resultant encoded string.
ESAPIStringOperation * ESAPICDecode (char *inputString, ESAPIEncodingType typeOfEncoding)
This function is used to decode the given string and return the resultant decoded string.
ESAPIStringOperation * ESAPICCanonicalizationForSpecificEncodingType (char *inputString, ESAPIEncodingType typeOfEncoding, bool strict)
This function is used to decode the given string to canonical form and return the resultant decoded string.
ESAPIStringOperation * ESAPICCanonicalizationAllAvailableEncodings (char *inputString, bool strict)
This function is used to decode the given string to canonical form and return the resultant decoded string.
Variables
const int numberOfAvailableCodecs = 2
ESAPIStringOperation *(* encodingFunctionsArray [2])(char *) = { ESAPICUrlEncoderEncode , ESAPICBase64EncoderEncode }
ESAPIStringOperation *(* decodingFunctionsArray [2])(char *) = { ESAPICUrlEncoderDecode , ESAPICBase64EncoderDecode }
Function Documentation
ESAPIStringOperation* ESAPICCanonicalizationAllAvailableEncodings (char * inputString, bool strict)
This function is used to decode the given string to canonical form and return the resultant decoded string.
NOTE: This function canonicalizes for all available encodings.
Parameters
inputString - The string to be encoded.
typeOfEncoding - The type of encoding required
strict - If the strict flag is set, the decoding will fail in case of Multiple encoding/Mixed encoding etc.,
{
        char inputString[] = "sometext";
        ESAPIStringOperation * decodedStringOperation =
      ESAPICCanonicalizationAllAvailableEncodings (inputString, false);
        if (decodedStringOperation->operationSuccessful)
        
                char * decodedString = decodedStringOperation->returnString;
                //Use the decodedString for operations.
                free (decodedString);
        
        else
        
                char * errorDescription = encodedStringOperation->
      errorDescription;
                //The decoding has failed. Manage accordingly.
                free (errorDescription);
        
        free (decodedStringOperation);
 }
Definition at line 121 of file ESAPICEncoder.c.
References ESAPIStringOperation::errorDescription, ESAPICCanonicalizationForSpecificEncodingType(), numberOfAvailableCodecs, ESAPIStringOperation::operationSuccessful, and ESAPIStringOperation::returnString.
ESAPIStringOperation* ESAPICCanonicalizationForSpecificEncodingType (char * inputString, ESAPIEncodingType typeOfEncoding, bool strict)
This function is used to decode the given string to canonical form and return the resultant decoded string.
NOTE: This function canonicalizes for only one given encoding type.
Parameters
inputString - The string to be encoded.
typeOfEncoding - The type of encoding required
strict - If the strict flag is set, the decoding will fail in case of Multiple encoding/Mixed encoding etc.,
{
 char inputString[] = "sometext";
 ESAPIStringOperation * decodedStringOperation = ESAPICanonicalizationForSpecific
      EncodingType (inputString, ESAPIEncodingTypePercentEncoding, false);
 if (decodedStringOperation->operationSuccessful)
 
        char * decodedString = decodedStringOperation->returnString;
        //Use the decodedString for operations.
        free (decodedString);
 
 else
 
        char * errorDescription = encodedStringOperation->errorDescription;
        //The decoding has failed. Manage accordingly.
        free (errorDescription);
 
 free (decodedStringOperation);
 }
Definition at line 59 of file ESAPICEncoder.c.
References ESAPIStringOperation::errorDescription, ESAPICDecode(), ESAPIStringOperation::operationSuccessful, and ESAPIStringOperation::returnString.
Referenced by ESAPICCanonicalizationAllAvailableEncodings(), and main().
ESAPIStringOperation* ESAPICDecode (char * inputString, ESAPIEncodingType typeOfEncoding)
This function is used to decode the given string and return the resultant decoded string.
Parameters
inputString - The string to be encoded.
typeOfEncoding - The type of encoding required
{
        char inputString[] = "sometext";
        ESAPIStringOperation * decodedStringOperation = ESAPIDecode (inputString
      , ESAPIEncodingTypePercentEncoding);
        if (decodedStringOperation->operationSuccessful)
        
                char * decodedString = decodedStringOperation->returnString;
                //Use the decodedString for operations.
                free (decodedString);
        
        else
        
                char * errorDescription = encodedStringOperation->
      errorDescription;
                //The decoding has failed. Manage accordingly.
                free (errorDescription);
        
        free (decodedStringOperation);
 }
Definition at line 40 of file ESAPICEncoder.c.
References decodingFunctionsArray, ESAPIStringOperation::errorDescription, numberOfAvailableCodecs, and ESAPIStringOperation::operationSuccessful.
Referenced by ESAPICCanonicalizationForSpecificEncodingType().
ESAPIStringOperation* ESAPICEncode (char * inputString, ESAPIEncodingType typeOfEncoding)
This function is used to encode the given string and return the resultant encoded string.
Parameters
inputString - The string to be encoded.
typeOfEncoding - The type of encoding required.
Returns
encodedString - The encoded string using the ESAPIEncodingType is returned.
{
        char inputString[] = "sometext";
        ESAPIStringOperation * encodedStringOperation = ESAPIEncode (inputString
      , ESAPIEncodingTypePercentEncoding);
        if (encodedStringOperation->operationSuccessful)
        
                char * encodedString = encodedStringOperation->returnString;
                //Use the encodedString for operations.
                free (encodedString);
        
        else
        
                char * errorDescription = encodedStringOperation->
      errorDescription;
                //The encoding has failed. Manage accordingly.
                free (errorDescription);
        
        free (encodedStringOperation);
 }
Definition at line 21 of file ESAPICEncoder.c.
References encodingFunctionsArray, ESAPIStringOperation::errorDescription, numberOfAvailableCodecs, and ESAPIStringOperation::operationSuccessful.
Referenced by main().
Variable Documentation
ESAPIStringOperation*(* decodingFunctionsArray[2])(char *) = { ESAPICUrlEncoderDecode , ESAPICBase64EncoderDecode }
Definition at line 19 of file ESAPICEncoder.c.
Referenced by ESAPICDecode().
ESAPIStringOperation*(* encodingFunctionsArray[2])(char *) = { ESAPICUrlEncoderEncode , ESAPICBase64EncoderEncode }
Definition at line 18 of file ESAPICEncoder.c.
Referenced by ESAPICEncode().
const int numberOfAvailableCodecs = 2
Definition at line 17 of file ESAPICEncoder.c.
Referenced by ESAPICCanonicalizationAllAvailableEncodings(), ESAPICDecode(), and ESAPICEncode().