/Users/deepaksubramanian/Documents/Folder of Documents/XCode/ESAPI_COMPLETE/branches/ESAPI Branch Cuckoo/build/Release/ESAPI.framework/Versions/A/Headers/ESAPICEncoder.h File Reference
#include <stdlib.h>
#include `ESAPICAuxiliaryFunctions.h`
Enumerations
enum ESAPIEncodingType {
ESAPIEncodingTypePercentEncoding = 0,
ESAPIEncodingTypeURLEncoding = 0,
ESAPIEncodingTypeBase64Encoding = 1,
ESAPIEncodingTypePercentEncoding = 0,
ESAPIEncodingTypeURLEncoding = 0,
ESAPIEncodingTypeBase64Encoding = 1
 }
This is the header of the ESAPI C Encoder Functions.
Functions
ESAPIStringOperation * ESAPICEncode (char *inputString, ESAPIEncodingType typeOfEncoding)
This function is used to encode the given string and return the resultant encoded string.
ESAPIStringOperation * ESAPICDecode (char *inputString, ESAPIEncodingType typeOfEncoding)
This function is used to decode the given string and return the resultant decoded string.
ESAPIStringOperation * ESAPICCanonicalizationForSpecificEncodingType (char *inputString, ESAPIEncodingType typeOfEncoding, bool strict)
This function is used to decode the given string to canonical form and return the resultant decoded string.
ESAPIStringOperation * ESAPICCanonicalizationAllAvailableEncodings (char *inputString, bool strict)
This function is used to decode the given string to canonical form and return the resultant decoded string.
Enumeration Type Documentation
enum ESAPIEncodingType
This is the header of the ESAPI C Encoder Functions.
These function are designed to assist in encoding functionality in various scenarios. `
 Encoding:
Currently Supported Encodings:
URL Encoding
The OWASP ESAPI C Library is still not complete and the release is a ALPHA QUALITY release. Kindly let us know of any bugs through email to deepak.subramanian@owasp.org The enum that describes the possible encodings available with the ESAPI Library
Enumerator:
ESAPIEncodingTypePercentEncoding
 Percentage encoding is generally used in the get and post requests to cate for multiple parameters.
ESAPIEncodingTypeURLEncoding
 Same as percent encoding. Catering for redundancy of names.
ESAPIEncodingTypeBase64Encoding
 The base64 encoding.
ESAPIEncodingTypePercentEncoding
 Percentage encoding is generally used in the get and post requests to cate for multiple parameters.
ESAPIEncodingTypeURLEncoding
 Same as percent encoding. Catering for redundancy of names.
ESAPIEncodingTypeBase64Encoding
 The base64 encoding.
Definition at line 47 of file ESAPICEncoder.h.
Function Documentation
ESAPIStringOperation* ESAPICCanonicalizationAllAvailableEncodings (char * inputString, bool strict)
This function is used to decode the given string to canonical form and return the resultant decoded string.
NOTE: This function canonicalizes for all available encodings.
Parameters
inputString - The string to be encoded.
typeOfEncoding - The type of encoding required
strict - If the strict flag is set, the decoding will fail in case of Multiple encoding/Mixed encoding etc.,
{
        char inputString[] = "sometext";
        ESAPIStringOperation * decodedStringOperation =
      ESAPICCanonicalizationAllAvailableEncodings (inputString, false);
        if (decodedStringOperation->operationSuccessful)
        
                char * decodedString = decodedStringOperation->returnString;
                //Use the decodedString for operations.
                free (decodedString);
        
        else
        
                char * errorDescription = encodedStringOperation->errorDescriptio
      n;
                //The decoding has failed. Manage accordingly.
                free (errorDescription);
        
        free (decodedStringOperation);
 }
Definition at line 121 of file ESAPICEncoder.c.
ESAPIStringOperation* ESAPICCanonicalizationForSpecificEncodingType (char * inputString, ESAPIEncodingType typeOfEncoding, bool strict)
This function is used to decode the given string to canonical form and return the resultant decoded string.
NOTE: This function canonicalizes for only one given encoding type.
Parameters
inputString - The string to be encoded.
typeOfEncoding - The type of encoding required
strict - If the strict flag is set, the decoding will fail in case of Multiple encoding/Mixed encoding etc.,
{
 char inputString[] = "sometext";
 ESAPIStringOperation * decodedStringOperation = ESAPICanonicalizationForSpecific
      EncodingType (inputString, ESAPIEncodingTypePercentEncoding, false);
 if (decodedStringOperation->operationSuccessful)
 
        char * decodedString = decodedStringOperation->returnString;
        //Use the decodedString for operations.
        free (decodedString);
 
 else
 
        char * errorDescription = encodedStringOperation->errorDescription;
        //The decoding has failed. Manage accordingly.
        free (errorDescription);
 
 free (decodedStringOperation);
 }
Definition at line 59 of file ESAPICEncoder.c.
Referenced by ESAPICCanonicalizationAllAvailableEncodings(), and main().
ESAPIStringOperation* ESAPICDecode (char * inputString, ESAPIEncodingType typeOfEncoding)
This function is used to decode the given string and return the resultant decoded string.
Parameters
inputString - The string to be encoded.
typeOfEncoding - The type of encoding required
{
        char inputString[] = "sometext";
        ESAPIStringOperation * decodedStringOperation = ESAPIDecode (inputString
      , ESAPIEncodingTypePercentEncoding);
        if (decodedStringOperation->operationSuccessful)
        
                char * decodedString = decodedStringOperation->returnString;
                //Use the decodedString for operations.
                free (decodedString);
        
        else
        
                char * errorDescription = encodedStringOperation->errorDescriptio
      n;
                //The decoding has failed. Manage accordingly.
                free (errorDescription);
        
        free (decodedStringOperation);
 }
Definition at line 40 of file ESAPICEncoder.c.
Referenced by ESAPICCanonicalizationForSpecificEncodingType().
ESAPIStringOperation* ESAPICEncode (char * inputString, ESAPIEncodingType typeOfEncoding)
This function is used to encode the given string and return the resultant encoded string.
Parameters
inputString - The string to be encoded.
typeOfEncoding - The type of encoding required.
Returns
encodedString - The encoded string using the ESAPIEncodingType is returned.
{
        char inputString[] = "sometext";
        ESAPIStringOperation * encodedStringOperation = ESAPIEncode (inputString
      , ESAPIEncodingTypePercentEncoding);
        if (encodedStringOperation->operationSuccessful)
        
                char * encodedString = encodedStringOperation->returnString;
                //Use the encodedString for operations.
                free (encodedString);
        
        else
        
                char * errorDescription = encodedStringOperation->
      errorDescription;
                //The encoding has failed. Manage accordingly.
                free (errorDescription);
        
        free (encodedStringOperation);
 }
Definition at line 21 of file ESAPICEncoder.c.
Referenced by main().