.TH "/Users/deepaksubramanian/Documents/Folder of Documents/XCode/ESAPI_COMPLETE/branches/ESAPI Branch Cuckoo/Pure C functions/ESAPICommonFunctions/ESAPICAuxiliaryFunctions.c" 3 "Sat Jul 9 2011" "Version v0.0.1 (Alpha)" "ESAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/deepaksubramanian/Documents/Folder of Documents/XCode/ESAPI_COMPLETE/branches/ESAPI Branch Cuckoo/Pure C functions/ESAPICommonFunctions/ESAPICAuxiliaryFunctions.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ESAPICAuxiliaryFunctions.h'\fP
.br
\fC#include <math.h>\fP
.br
\fC#include <ctype.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char \fBfrom_hex\fP (char ch)"
.br
.RI "\fIConverts a hex character to its integer value. \fP"
.ti -1c
.RI "char \fBto_hex\fP (char code)"
.br
.RI "\fIConverts an integer value to its hex character. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "char from_hex (charch)"
.PP
Converts a hex character to its integer value. Returns the decimal value for a given hexadecimal character. 
.PP
Definition at line 17 of file ESAPICAuxiliaryFunctions.c.
.SS "char to_hex (charcode)"
.PP
Converts an integer value to its hex character. Returns the hexadecimal value for a given decimal character. 
.PP
Definition at line 25 of file ESAPICAuxiliaryFunctions.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for ESAPI from the source code.
