.TH "/Users/deepaksubramanian/Documents/Folder of Documents/XCode/ESAPI_COMPLETE/branches/ESAPI Branch Cuckoo/Pure C functions/ESAPIEncoder/urlEncoder.c" 3 "Sat Jul 9 2011" "Version v0.0.1 (Alpha)" "ESAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/deepaksubramanian/Documents/Folder of Documents/XCode/ESAPI_COMPLETE/branches/ESAPI Branch Cuckoo/Pure C functions/ESAPIEncoder/urlEncoder.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <math.h>\fP
.br
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <ctype.h>\fP
.br
\fC#include <string.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char \fBfrom_hex\fP (char ch)"
.br
.RI "\fIReturns the decimal value for a given hexadecimal character. \fP"
.ti -1c
.RI "char \fBto_hex\fP (char code)"
.br
.RI "\fIReturns the hexadecimal value for a given decimal character. \fP"
.ti -1c
.RI "char * \fBurl_encode\fP (char *str)"
.br
.ti -1c
.RI "char * \fBurl_decode\fP (char *str)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char from_hex (charch)"
.PP
Returns the decimal value for a given hexadecimal character. This code has been downloaded from http://www.geekhideout.com/urlcode.shtml on April 16, 2011
.PP
\fBParameters:\fP
.RS 4
\fIhexadecimalChar\fP - The given hexadecimal character
.RE
.PP
\fBReturns:\fP
.RS 4
- The equivalent decimal value
.RE
.PP
{ 
.PP
.nf
      char int = from_hex('a');

.fi
.PP
 } 
.PP
Definition at line 9 of file urlEncoder.c.
.PP
Referenced by ESAPICUrlEncoderDecode(), and url_decode().
.SS "char to_hex (charcode)"
.PP
Returns the hexadecimal value for a given decimal character. This code has been downloaded from http://www.geekhideout.com/urlcode.shtml on April 16, 2011
.PP
\fBParameters:\fP
.RS 4
\fIdecimalChar\fP - The given decimal character
.RE
.PP
\fBReturns:\fP
.RS 4
- The hexadecimal equivalent value
.RE
.PP
{ 
.PP
.nf
       char int = to_hex('9');

.fi
.PP
 } 
.PP
Definition at line 15 of file urlEncoder.c.
.PP
Referenced by ESAPICUrlEncoderEncode(), and url_encode().
.SS "char* url_decode (char *str)"
.PP
Definition at line 44 of file urlEncoder.c.
.PP
References from_hex().
.SS "char* url_encode (char *str)"
.PP
Definition at line 23 of file urlEncoder.c.
.PP
References to_hex().
.SH "Author"
.PP 
Generated automatically by Doxygen for ESAPI from the source code.
