/Users/deepaksubramanian/Documents/Folder of Documents/XCode/ESAPI_COMPLETE/branches/ESAPI Branch Cuckoo/Pure C functions/ESAPIEncoder/urlEncoder.c File Reference
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include <string.h>
Functions
char from_hex (char ch)
Returns the decimal value for a given hexadecimal character.
char to_hex (char code)
Returns the hexadecimal value for a given decimal character.
char * url_encode (char *str)
char * url_decode (char *str)
Function Documentation
char from_hex (char ch)
Returns the decimal value for a given hexadecimal character.
This code has been downloaded from http://www.geekhideout.com/urlcode.shtml on April 16, 2011
Parameters
hexadecimalChar - The given hexadecimal character
Returns
- The equivalent decimal value
{
        char int = from_hex('a');
 }
Definition at line 9 of file urlEncoder.c.
Referenced by ESAPICUrlEncoderDecode(), and url_decode().
char to_hex (char code)
Returns the hexadecimal value for a given decimal character.
This code has been downloaded from http://www.geekhideout.com/urlcode.shtml on April 16, 2011
Parameters
decimalChar - The given decimal character
Returns
- The hexadecimal equivalent value
{
        char int = to_hex('9');
 }
Definition at line 15 of file urlEncoder.c.
Referenced by ESAPICUrlEncoderEncode(), and url_encode().
char* url_decode (char * str)
Definition at line 44 of file urlEncoder.c.
References from_hex().
char* url_encode (char * str)
Definition at line 23 of file urlEncoder.c.
References to_hex().