/Users/deepaksubramanian/Documents/Folder of Documents/XCode/ESAPI_COMPLETE/branches/ESAPI Branch Cuckoo/build/Release/ESAPI.framework/Versions/A/Headers/ESAPICAuxiliaryFunctions.h File Reference
#include <stdbool.h>
#include <string.h>
Data Structures
struct ESAPIStringOperation
Sends the results and sets the required flags.
Functions
char from_hex (char hexadecimalChar)
Returns the decimal value for a given hexadecimal character.
char to_hex (char decimalChar)
Returns the hexadecimal value for a given decimal character.
Function Documentation
char from_hex (char ch)
Returns the decimal value for a given hexadecimal character.
This code has been downloaded from http://www.geekhideout.com/urlcode.shtml on April 16, 2011
Parameters
hexadecimalChar - The given hexadecimal character
Returns
- The equivalent decimal value
{
        char int = from_hex('a');
 }
Definition at line 17 of file ESAPICAuxiliaryFunctions.c.
Referenced by ESAPICUrlEncoderDecode(), and url_decode().
char to_hex (char code)
Returns the hexadecimal value for a given decimal character.
This code has been downloaded from http://www.geekhideout.com/urlcode.shtml on April 16, 2011
Parameters
decimalChar - The given decimal character
Returns
- The hexadecimal equivalent value
{
        char int = to_hex('9');
 }
Definition at line 25 of file ESAPICAuxiliaryFunctions.c.
Referenced by ESAPICUrlEncoderEncode(), and url_encode().