.TH "/Users/deepaksubramanian/Documents/Folder of Documents/XCode/ESAPI_COMPLETE/branches/ESAPI Branch Cuckoo/ESAPIEncoder/ESAPIEncoder.h" 3 "Sat Jul 9 2011" "Version v0.0.1 (Alpha)" "ESAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/deepaksubramanian/Documents/Folder of Documents/XCode/ESAPI_COMPLETE/branches/ESAPI Branch Cuckoo/ESAPIEncoder/ESAPIEncoder.h \- 
.SH SYNOPSIS
.br
.PP
\fC#import <Foundation/Foundation.h>\fP
.br
\fC#import 'ESAPICEncoder.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBNSString(ESAPIEncoderMethods)\fP"
.br
.RI "\fIOverload of the \fBNSString\fP method for encoding. \fP"
.ti -1c
.RI "class \fBESAPIEncoder\fP"
.br
.RI "\fIThis is the interface. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ESAPI from the source code.
