.TH "/Users/deepaksubramanian/Documents/Folder of Documents/XCode/ESAPI_COMPLETE/branches/ESAPI Branch Cuckoo/Pure C functions/ESAPIEncoder/Example/ESAPIEncoderExample_XCodeProj/main.c" 3 "Sat Jul 9 2011" "Version v0.0.1 (Alpha)" "ESAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/deepaksubramanian/Documents/Folder of Documents/XCode/ESAPI_COMPLETE/branches/ESAPI Branch Cuckoo/Pure C functions/ESAPIEncoder/Example/ESAPIEncoderExample_XCodeProj/main.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include 'ESAPICEncoder.h'\fP
.br
\fC#include <curses.h>\fP
.br
\fC#include <string.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (void)"
.PP
Definition at line 14 of file main.c.
.PP
References ESAPIStringOperation::errorDescription, ESAPICCanonicalizationForSpecificEncodingType(), ESAPICEncode(), ESAPIEncodingTypeBase64Encoding, ESAPIStringOperation::operationSuccessful, and ESAPIStringOperation::returnString.
.SH "Author"
.PP 
Generated automatically by Doxygen for ESAPI from the source code.
